### ISSUE TITLE
How to default VS Code terminal to fish?

### ISSUE THREAD

**Issue by nvlgzr** [axonasif/dotfiles#2]
First of all, thanks for this! I found your post(s) on Discord, and it seemed like exactly what I was looking for (after spending several hours pounding my head against GitPod's docs).

# 🙇🏽

By any chance do you know how to make VS Code default consistently to _fish_ without manual effort?

I found advice to put this in settings.json…

    "terminal.integrated.shell.linux": "/usr/bin/fish" 

…but of course, when I make that change in one GitPod workspace, that doesn't propagate to new workspaces. Do I have to add my own `settings.json` hack, or is this something your `dotfiles` can already be configured to handle?

**Comment by nvlgzr** [comment]
Oops. Wait. I think I was "doing it wrong".

After further inspection, it seems like I had a workspace that was opening a blank bash terminal at first, but all future terminals after that started with fish. So i guess…ignore everything above except the _thanks!_ 😁

**Comment by axonasif** [comment]
> After further inspection, it seems like I had a workspace that was opening a blank bash terminal at first, but all future terminals after that started with fish. So i guess…ignore everything above except the thanks! 😁

What you're experiencing is valid, see https://github.com/gitpod-io/gitpod/issues/9531

**Comment by axonasif** [comment]
And BTW, this dotfiles repo applies a workaround to enforce the use of `fish` on `.gitpod.yml:tasks` terminals after the commands from a `task` is done executing in `bash`. We will have a better officially implemented fix for this in the future.
